import type { Tool } from './tools'
import { getActiveCombos } from './combos'

export interface GenerateOptions {
  /** toolId → selected version string (e.g. { react: '19', nextjs: '15' }) */
  selectedVersions?: Record<string, string>
  /** Free-form team-specific rules appended to every generated config */
  customRules?: string
}

export interface OutputFile {
  path: string
  content: string
}

export interface Assistant {
  id: string
  name: string
  logo: string
  description: string
  badge: string
  /** Plain-text steps shown in the "How to use" section. Wrap filenames in backticks for code formatting. */
  usageSteps: string[]
  generate: (tools: Tool[], projectName: string, options?: GenerateOptions) => OutputFile[]
}

// ─── Shared builders ─────────────────────────────────────────────────────────

/** Full skill block: overview + patterns + gotchas + quickstart */
function toolSkillBlock(tool: Tool): string {
  return `## ${tool.emoji} ${tool.name}

${tool.knowledge.overview}

${tool.knowledge.patterns}

${tool.knowledge.gotchas}

### Quick Start
${tool.knowledge.quickstart}
`
}

/** Compact best-practice checklist for a single tool — injected into every config */
function toolRulesBlock(tool: Tool): string {
  const rules = tool.bestPractices.map(r => `- ${r}`).join('\n')
  return `### ${tool.emoji} ${tool.name}\n${rules}`
}

/** Combined rules section across all selected tools, including active combo rules */
function stackRulesSection(tools: Tool[], options?: GenerateOptions): string {
  const combos = getActiveCombos(tools.map(t => t.id))
  const comboSection = combos.length > 0
    ? `\n## Cross-Tool Rules\n\n> These rules apply specifically to the combination of tools you selected.\n\n${combos.map(c => `### ${c.label}\n${c.rules.map(r => `- ${r}`).join('\n')}`).join('\n\n')}\n`
    : ''
  const customSection = options?.customRules?.trim()
    ? `\n## Team Rules\n\n${options.customRules.trim()}\n`
    : ''
  return `## Stack-Specific Rules

> These rules are non-negotiable. Enforce them on every code change.

${tools.map(toolRulesBlock).join('\n\n')}
${comboSection}${customSection}`
}

/** Stack header listing tools with selected versions */
function stackHeader(tools: Tool[], options?: GenerateOptions): string {
  return tools.map(t => {
    const version = options?.selectedVersions?.[t.id]
    return `- **${t.name}${version ? ` v${version}` : ''}** — ${t.description}`
  }).join('\n')
}

/** Combo notes (patterns/gotchas) for active tool combinations */
function comboNotesSection(tools: Tool[]): string {
  const combos = getActiveCombos(tools.map(t => t.id))
  if (combos.length === 0) return ''
  return `\n---\n\n## Cross-Tool Patterns\n\n${combos.map(c => c.notes.trim()).join('\n\n---\n\n')}\n`
}

/** Generated-by header comment for markdown files */
function generatedHeader(): string {
  const date = new Date().toISOString().split('T')[0]
  return `[//]: # (Generated by context-kit on ${date} — re-generate at context-kit.dev)\n\n`
}

/** Stack-aware /plan command */
function planCommand(tools: Tool[]): string {
  const toolIds = new Set(tools.map(t => t.id))
  const extras: string[] = []
  if (toolIds.has('nextjs')) extras.push('- Identify whether this is a Server Component, Client Component, or Route Handler operation')
  if (toolIds.has('prisma') || toolIds.has('drizzle')) extras.push('- Check if any schema changes are needed and whether a migration is required')
  if (toolIds.has('supabase')) extras.push('- Check if this operation touches data covered by RLS policies')
  if (toolIds.has('trpc')) extras.push('- Determine if this belongs in an existing router or needs a new procedure')

  return `Before writing any code:
1. Restate the goal in one sentence
2. List the files that will change
3. Define the interface or contract first (types, function signatures, API shape)
4. Identify edge cases and error paths
5. Estimate complexity: S (< 1h) / M (half day) / L (full day+)${extras.length > 0 ? '\n' + extras.join('\n') : ''}
6. Wait for explicit approval before writing any implementation code
`
}

/** Stack-aware /code-review command */
function codeReviewCommand(tools: Tool[]): string {
  const toolIds = new Set(tools.map(t => t.id))
  const extras: string[] = []
  if (toolIds.has('supabase')) extras.push('- Check all new tables have RLS enabled and appropriate policies — tables without RLS are fully public')
  if (toolIds.has('authjs') || toolIds.has('supabase')) extras.push('- Verify all protected routes and API handlers check authentication before processing')
  if (toolIds.has('prisma') || toolIds.has('drizzle')) extras.push('- Check for N+1 query patterns — every relation should be fetched in a single query')
  if (toolIds.has('nextjs')) extras.push("- Confirm 'use client' is only added when the component truly needs browser APIs or interactivity")
  if (toolIds.has('openai') || toolIds.has('anthropic')) extras.push('- Verify all LLM outputs are validated before being used in business logic or rendered as HTML')

  return `Review the staged changes for:
- Correctness: does the logic do what is intended?
- Security: injection, auth bypass, data exposure, missing input validation
- Performance: N+1 queries, blocking operations, missing indexes, large payloads
- Types: no any, proper null/undefined handling, no unsafe type assertions
- Tests: are new code paths covered?
- Style: matches project conventions in this config file${extras.length > 0 ? '\n\nStack-specific checks:\n' + extras.join('\n') : ''}

Output findings as: [CRITICAL] / [WARNING] / [SUGGESTION]
`
}

/** Stack-aware /build-fix command */
function buildFixCommand(tools: Tool[]): string {
  const toolIds = new Set(tools.map(t => t.id))
  const extras: string[] = []
  if (toolIds.has('prisma')) extras.push("- Check if 'npx prisma generate' needs to run — the generated client may be out of sync with the schema")
  if (toolIds.has('drizzle')) extras.push('- Check if there are pending migrations: npx drizzle-kit generate followed by npx drizzle-kit migrate')
  if (toolIds.has('nextjs')) extras.push('- Check if the error is in a Server Component, Client Component, or Edge Runtime context — each has different restrictions')

  return `Given a build or type error:
1. Read the full error message — do not skim it
2. Identify the root cause, not just the symptom
3. Categorise: type error / import error / missing module / runtime API mismatch${extras.length > 0 ? '\n\nStack-specific checks:\n' + extras.join('\n') : ''}
4. Fix the root cause — do not suppress errors with // @ts-ignore or any casts
5. Verify the fix does not break other parts of the codebase
`
}

/** Generate numbered ADR files for all selected tools */
function generateADRFiles(tools: Tool[]): OutputFile[] {
  const files: OutputFile[] = []

  // ADR template for future decisions
  files.push({
    path: 'docs/decisions/ADR-000-template.md',
    content: `# ADR-XXX: [Short title of the decision]

## Status
<!-- Proposed | Accepted | Deprecated | Superseded by ADR-XXX -->
Proposed

## Date
${new Date().toISOString().split('T')[0]}

## Context
<!--
What is the situation that forces us to make this decision?
What constraints are we working within?
-->

## Decision
<!--
What did we decide to do?
Be specific about the chosen approach.
-->

## Consequences

### Positive
-

### Negative
-

## Alternatives Considered
<!--
What other options did we evaluate?
Why were they rejected?
-->

## References
-
`,
  })

  // ADR index
  const indexRows = tools
    .map((t, i) => `| ADR-${String(i + 1).padStart(3, '0')} | ${t.adr.title} | Accepted |`)
    .join('\n')

  files.push({
    path: 'docs/decisions/ADR-INDEX.md',
    content: `# Architecture Decision Records

This directory contains ADRs (Architecture Decision Records) for this project.
Each ADR documents a significant architectural choice: what was decided, why, and what the trade-offs are.

## What is an ADR?
An ADR is a short document that captures an important architectural decision. It records:
- **Context**: what situation forced the decision
- **Decision**: what was chosen
- **Consequences**: what becomes easier or harder as a result

## Index

| ADR | Title | Status |
|-----|-------|--------|
${indexRows}

## How to add a new ADR
1. Copy \`ADR-000-template.md\`
2. Number it sequentially (ADR-${String(tools.length + 1).padStart(3, '0')}-short-title.md)
3. Fill in all sections
4. Update this index
5. Commit alongside the code change it documents
`,
  })

  // Pre-generated ADR per selected tool
  for (const [i, tool] of tools.entries()) {
    const num = String(i + 1).padStart(3, '0')
    const slug = tool.id
    const { adr } = tool

    files.push({
      path: `docs/decisions/ADR-${num}-${slug}.md`,
      content: `# ADR-${num}: ${adr.title}

## Status
Accepted

## Date
${new Date().toISOString().split('T')[0]}

## Context
${adr.context}

## Decision
${adr.decision}

## Consequences

### Positive
${adr.positives.map(p => `- ${p}`).join('\n')}

### Negative
${adr.negatives.map(n => `- ${n}`).join('\n')}

## Alternatives Considered
${adr.alternatives.map(a => `- ${a}`).join('\n')}
`,
    })
  }

  return files
}

function systemPromptContent(tools: Tool[], projectName: string, options?: GenerateOptions): string {
  const toolNames = tools.map(t => t.name).join(', ')
  return `${generatedHeader()}# AI Assistant Context — ${projectName}

You are an expert developer assistant for a project using: **${toolNames}**.

## Universal Rules
- Prefer immutability — never mutate state directly
- Proper error handling with try/catch on all async operations
- Validate all user input at system boundaries
- No hardcoded secrets — use environment variables
- Write tests alongside features — aim for 80%+ coverage
- TypeScript strict mode — no \`any\` types, no implicit returns

---

${stackRulesSection(tools, options)}

---

## Reference: Patterns, Gotchas & Quickstarts

${tools.map(toolSkillBlock).join('\n---\n\n')}
${comboNotesSection(tools)}`
}

// ─── Assistants ───────────────────────────────────────────────────────────────

export const ASSISTANTS: Assistant[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    logo: '🤖',
    badge: 'claude.ai/code',
    description: 'CLAUDE.md + per-tool skill files in .claude/skills/',
    usageSteps: [
      'Extract the zip into your project root',
      'The `CLAUDE.md` is automatically loaded by Claude Code',
      'Skills in `.claude/skills/` are loaded on demand',
      'Use `/plan`, `/code-review`, `/build-fix` commands',
    ],
    generate(tools, projectName, options) {
      const files: OutputFile[] = []

      // Root CLAUDE.md
      files.push({
        path: 'CLAUDE.md',
        content: `${generatedHeader()}# ${projectName}

## Stack
${stackHeader(tools, options)}

## Universal Rules

### Code Style
- No \`any\` types — define proper interfaces
- Immutability: never mutate objects/arrays in place
- No console.log in production code — use a logger
- Proper error handling with try/catch on all async operations

### Testing
- TDD: write tests first for non-trivial logic
- 80% minimum line coverage
- Unit tests for utilities, integration tests for APIs, E2E for critical flows

### Security
- No hardcoded secrets — environment variables only
- Validate all user input with Zod or equivalent
- Sanitize data before DB writes
- HTTPS everywhere, secure cookies with httpOnly + sameSite

### Git Workflow
- Conventional commits: \`feat:\`, \`fix:\`, \`refactor:\`, \`test:\`, \`docs:\`
- Never commit to main directly
- All tests must pass before merge

---

${stackRulesSection(tools, options)}

---

## Skills Loaded
The following tool-specific skills are in \`.claude/skills/\`:
${tools.map(t => `- [${t.name}](.claude/skills/${t.id}.md)`).join('\n')}

## Available Commands
- \`/plan\` — create an implementation plan before coding
- \`/code-review\` — review staged changes for quality and security
- \`/build-fix\` — diagnose and fix build errors
- \`/tdd\` — test-driven development workflow

## Environment Variables
\`\`\`bash
# Copy .env.example → .env.local and fill in values
\`\`\`
`,
      })

      // Per-tool skill files
      for (const tool of tools) {
        files.push({
          path: `.claude/skills/${tool.id}.md`,
          content: `---
name: ${tool.name.toLowerCase().replace(/\s+/g, '-')}
description: Patterns, gotchas, and quickstart for ${tool.name}
---

# ${tool.emoji} ${tool.name}

> ${tool.description}

## Best Practices — Enforce These
${tool.bestPractices.map(r => `- ${r}`).join('\n')}

## Overview
${tool.knowledge.overview}

${tool.knowledge.patterns}

${tool.knowledge.gotchas}

## Quick Start
${tool.knowledge.quickstart}
`,
        })
      }

      // Slash commands
      files.push({
        path: '.claude/commands/plan.md',
        content: planCommand(tools),
      })

      files.push({
        path: '.claude/commands/code-review.md',
        content: codeReviewCommand(tools),
      })

      files.push({
        path: '.claude/commands/build-fix.md',
        content: buildFixCommand(tools),
      })

      files.push({
        path: '.claude/commands/adr.md',
        content: `Create a new Architecture Decision Record for the decision described in $ARGUMENTS.

Steps:
1. Read docs/decisions/ADR-INDEX.md to find the next ADR number
2. Create docs/decisions/ADR-XXX-short-slug.md using this format:

\`\`\`
# ADR-XXX: [Title]

## Status
Proposed

## Date
[today's date]

## Context
[What situation forces this decision? What constraints exist?]

## Decision
[What exactly was decided? Be specific.]

## Consequences

### Positive
- [benefit 1]

### Negative
- [trade-off 1]

## Alternatives Considered
- [alternative]: [why rejected]
\`\`\`

3. Add the new ADR to the index table in docs/decisions/ADR-INDEX.md
4. Summarize the decision in one sentence

Usage: /adr "why we chose Redis over in-memory caching"
`,
      })

      files.push({
        path: '.claude/commands/architecture.md',
        content: `Generate or update ARCHITECTURE.md for this project.

Steps:
1. Read the project structure (src/, app/, lib/, components/, routes/, etc.)
2. Identify the main layers and how they interact
3. Read package.json for dependencies
4. Check docs/decisions/ for existing ADRs
5. Write ARCHITECTURE.md covering:

\`\`\`markdown
# Architecture — [project name]

## Overview
[2-3 sentence description of what the system does and its primary users]

## System Diagram
[ASCII diagram showing main components and data flow]

## Layers

### [Layer name] (e.g., Presentation, API, Domain, Data)
- **Purpose**: ...
- **Key files**: ...
- **Responsibilities**: ...

## Data Flow
[Describe the path of a typical request from entry to response]

## Key Design Decisions
[Link to relevant ADRs in docs/decisions/]

## External Dependencies
| Service | Purpose | Config |
|---------|---------|--------|
| ...     | ...     | ...    |

## Environment Variables
[List required env vars and their purpose]
\`\`\`

6. If ARCHITECTURE.md already exists, update it in-place rather than replacing it.
`,
      })

      // ADR files — included in every assistant's output
      for (const adrFile of generateADRFiles(tools)) {
        files.push(adrFile)
      }

      files.push({
        path: '.env.example',
        content: generateEnvExample(tools),
      })

      return files
    },
  },

  {
    id: 'cursor',
    name: 'Cursor',
    logo: '🖱️',
    badge: 'cursor.com',
    description: 'Single .cursorrules file with full stack context',
    usageSteps: [
      'Extract the zip into your project root',
      'Cursor automatically reads `.cursorrules` for every file in the project',
      'Reopen Cursor to pick up the new rules',
    ],
    generate(tools, projectName, options) {
      return [
        {
          path: '.cursorrules',
          content: `# Generated by context-kit on ${new Date().toISOString().split('T')[0]} — re-generate at context-kit.dev
# ${projectName} — Cursor Rules

## Project Stack
${stackHeader(tools, options)}

## Universal Rules
- TypeScript strict mode — no \`any\` types
- Immutability — never mutate state directly
- Async/await with try/catch — no unhandled rejections
- Validate user inputs at boundaries (Zod preferred)
- No hardcoded secrets — use environment variables
- Write tests for all non-trivial logic

## Commit Format
Conventional commits: feat: / fix: / refactor: / test: / docs:

---

${stackRulesSection(tools, options)}

---

${tools.map(toolSkillBlock).join('\n---\n\n')}
${comboNotesSection(tools)}
---

## General Instructions
- When asked to build a feature, start with the interface/types, then implementation, then tests
- When fixing a bug, identify the root cause before writing any code
- Always check for existing patterns in the codebase before introducing new ones
- Prefer editing existing files over creating new ones
`,
        },
        {
          path: '.env.example',
          content: generateEnvExample(tools),
        },
        ...generateADRFiles(tools),
      ]
    },
  },

  {
    id: 'windsurf',
    name: 'Windsurf',
    logo: '🏄',
    badge: 'codeium.com/windsurf',
    description: 'Single .windsurfrules file',
    usageSteps: [
      'Extract the zip into your project root',
      'Windsurf automatically reads `.windsurfrules`',
      'Reload the workspace to apply context',
    ],
    generate(tools, projectName, options) {
      return [
        {
          path: '.windsurfrules',
          content: `# Generated by context-kit on ${new Date().toISOString().split('T')[0]} — re-generate at context-kit.dev
# ${projectName}

## Stack
${stackHeader(tools, options)}

## Universal Rules
- TypeScript only — no any types
- Immutable state — always return new objects/arrays
- Error boundaries: try/catch all async operations
- Validate inputs with Zod at system boundaries
- Env vars for all secrets, never hardcode
- 80%+ test coverage target

---

${stackRulesSection(tools, options)}

---

${tools.map(toolSkillBlock).join('\n---\n\n')}
${comboNotesSection(tools)}`,
        },
        {
          path: '.env.example',
          content: generateEnvExample(tools),
        },
        ...generateADRFiles(tools),
      ]
    },
  },

  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    logo: '🐙',
    badge: 'github.com/copilot',
    description: '.github/copilot-instructions.md — repo-level context',
    usageSteps: [
      'Extract the zip — the `.github/copilot-instructions.md` file is key',
      'Commit it to your repo — GitHub Copilot picks it up automatically in VS Code',
      'Requires Copilot Chat extension and GitHub Copilot subscription',
    ],
    generate(tools, projectName, options) {
      return [
        {
          path: '.github/copilot-instructions.md',
          content: `${generatedHeader()}# Copilot Instructions — ${projectName}

## Tech Stack
${stackHeader(tools, options)}

## Universal Rules
- TypeScript strict — avoid \`any\`, use unknown + type narrowing
- Prefer \`const\` over \`let\`, never \`var\`
- Async/await over Promises directly
- Named exports over default exports (easier to refactor)
- Error handling: explicit try/catch, never swallow errors silently

## Architecture Patterns
- Feature-based folder structure over type-based
- Thin controllers, fat services
- Validate at the boundary (API layer), trust internals
- Dependency injection for testability

---

${stackRulesSection(tools, options)}

---

${tools.map(toolSkillBlock).join('\n---\n\n')}
${comboNotesSection(tools)}`,
        },
        {
          path: '.env.example',
          content: generateEnvExample(tools),
        },
        ...generateADRFiles(tools),
      ]
    },
  },

  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    logo: '✨',
    badge: 'gemini cli',
    description: 'GEMINI.md — project context for Google Gemini CLI',
    usageSteps: [
      'Extract the zip into your project root',
      'Gemini CLI reads `GEMINI.md` automatically when run in the project',
    ],
    generate(tools, projectName, options) {
      return [
        {
          path: 'GEMINI.md',
          content: `${generatedHeader()}# ${projectName}

## Stack
${stackHeader(tools, options)}

## Universal Rules
- TypeScript strict mode — no any, proper interfaces
- Never mutate shared state
- Input validation with Zod at API boundaries
- No secrets in code — environment variables only
- Test coverage >= 80%

---

${stackRulesSection(tools, options)}

---

${tools.map(toolSkillBlock).join('\n---\n\n')}
${comboNotesSection(tools)}`,
        },
        {
          path: '.env.example',
          content: generateEnvExample(tools),
        },
        ...generateADRFiles(tools),
      ]
    },
  },

  {
    id: 'system-prompt',
    name: 'Any LLM',
    logo: '💬',
    badge: 'ChatGPT · Gemini · Mistral · any',
    description: 'Copy-paste system prompt for any chat LLM',
    usageSteps: [
      'Open `system-prompt.md` from the zip',
      'Copy the entire contents',
      'Paste it as the system prompt in ChatGPT, Claude.ai, Gemini, or any LLM chat',
      'For API use: pass it as the `system` message',
    ],
    generate(tools, projectName, options) {
      return [
        {
          path: 'system-prompt.md',
          content: systemPromptContent(tools, projectName, options),
        },
        {
          path: 'HOW-TO-USE.md',
          content: `# How to use this context kit

## For ChatGPT / Claude.ai / Gemini / any chat LLM:
1. Open a new conversation
2. Paste the contents of \`system-prompt.md\` as your first message (or system prompt if available)
3. Start asking questions about your stack — the LLM will have context for all your tools

## For API usage:
\`\`\`ts
const response = await openai.chat.completions.create({
  model: 'gpt-4o',
  messages: [
    { role: 'system', content: systemPrompt }, // contents of system-prompt.md
    { role: 'user', content: 'How do I set up a Prisma migration?' }
  ]
})
\`\`\`

## For LangChain / LlamaIndex:
Use the system-prompt.md content as the base system message in your chain.
`,
        },
        {
          path: '.env.example',
          content: generateEnvExample(tools),
        },
        ...generateADRFiles(tools),
      ]
    },
  },
]

// ─── Env example generator ────────────────────────────────────────────────────

function generateEnvExample(tools: Tool[]): string {
  const date = new Date().toISOString().split('T')[0]
  const lines: string[] = [
    `# Environment Variables — generated by context-kit on ${date}`,
    '# Copy this file to .env.local and fill in your values',
    '',
  ]

  const added = new Set<string>()

  for (const tool of tools) {
    if (tool.envVars && tool.envVars.length > 0) {
      lines.push(`# ${tool.name}`)
      for (const v of tool.envVars) {
        if (!added.has(v)) {
          lines.push(v)
          added.add(v)
        }
      }
      lines.push('')
    }
  }

  lines.push('# App')
  lines.push('NODE_ENV=development')
  lines.push('PORT=3000')

  return lines.join('\n')
}
